site_name: Java-GI
site_url: https://jwharm.github.io/java-gi/
nav:
    - Home: index.md
    - Basic usage: usage.md
    - Advanced usage: advanced.md
    - Examples: examples.md
    - Registering new types: register.md
    - Composite template classes: templates.md
    - Generating bindings: generate.md

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    logo: material/coffee

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
