name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 22

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
      with:
        gradle-version: 8.8
