name: MacOS - List gir files

on:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '00 1 * * 5'

jobs:
  update:
    name: MacOS - List gir files
    runs-on: macos-latest
    steps:
      - name: Install libraries
        run: |
          brew install libadwaita
          brew install gtk4
          brew install gtk+3
          brew install gstreamer
          brew install gst-plugins-base
          brew install gst-plugins-good
          brew install gobject-introspection
          brew install gtksourceview5
      - name: List gir files
        run: ls /usr/local/share/gir-1.0/

