name: Publish package to GitHub Packages

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install dependencies
        run: |
          dnf install -y gtk4-devel glib-devel libadwaita-devel gobject-introspection-devel
          dnf install -y gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-bad-free-devel
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
