name: Publish package

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install MkDocs
        run: pip3 install mkdocs
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: 'temurin'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Project and Publish Maven Packages
        run: ./bld download all publish
      - name: Build Site
        working-directory: website/
        run: mkdocs build
      - name: Create Site Artifact
        run: |
          mv website/site site
          mv glib/build/docs/javadoc site/glib
          mv gstreamer/build/docs/javadoc site/gstreamer
          mv gtk/build/docs/javadoc site/gtk
          mv adwaita/build/docs/javadoc site/adwaita
      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'site'
  pages:
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
