name: Publish package to GitHub Packages

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install Dependencies
        run: |
          dnf install -y gtk4-devel glib-devel libadwaita-devel gobject-introspection-devel
          dnf install -y gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-bad-free-devel
      - name: Publish Maven Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish javadoc --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Javadoc Artifact
        run: |
          mkdir javadoc
          mv generator/build/docs/javadoc javadoc/generator
          mv glib/build/docs/javadoc javadoc/glib
          mv gstreamer/build/docs/javadoc javadoc/gstreamer
          mv gtk4/build/docs/javadoc javadoc/gtk4
      - name: Upload Javadoc Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'javadoc'
  pages:
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1